/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GameItem: typeof import('./src/components/gameItem/gameItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponents: typeof import('./src/components/search/searchComponents.vue')['default']
    Swipe: typeof import('./src/components/swipeComponents/swipe.vue')['default']
    TitleContainer: typeof import('./src/components/titleContainer/titleContainer.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanIcon: typeof import('vant/es')['Icon']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
